"""Added created_at column in inquiry model

Revision ID: 1c461e4aa514
Revises: e3059fded25b
Create Date: 2022-09-30 07:57:52.436692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c461e4aa514'
down_revision = 'e3059fded25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiry', 'created_at')
    # ### end Alembic commands ###
