"""added reviewee_id column in Review model

Revision ID: 648a1fdab496
Revises: 1ea0b610cd37
Create Date: 2022-10-01 16:59:44.878245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648a1fdab496'
down_revision = '1ea0b610cd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('reviewee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'user', ['reviewee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'reviewee_id')
    # ### end Alembic commands ###
