"""added zip_code column in property model

Revision ID: 85631cb21917
Revises: 648a1fdab496
Create Date: 2022-10-03 23:42:07.471274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85631cb21917'
down_revision = '648a1fdab496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_review_reviewee_id_user'), 'user', ['reviewee_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_reviewee_id_user'), type_='foreignkey')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
