"""Added inquiry model

Revision ID: e3059fded25b
Revises: 
Create Date: 2022-09-30 07:53:28.925027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3059fded25b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('inquirer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inquirer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry')
    # ### end Alembic commands ###
